import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Bot, BrainCircuit, CheckCircle2, ChevronDown, ChevronUp, Clock3, Database, FileCheck2, RefreshCw, SearchCheck, ShieldCheck, Sparkles, UserRoundCheck } from 'lucide-react';
import { Alert, Box, Button, ButtonBase, Card, Chip, CircularProgress, Divider, IconButton, LinearProgress, Tooltip, Typography } from '@mui/material';

import { agentFlowSummary, agentStrategyLabel, fetchAgentFlow, normalizeAgentFlow, stageModeDescription, stageStatusLabel, type AgentFlowMode, type AgentFlowResponse, type AgentExecutionTrace } from '@/services/agent-flow-service';
import { ErrorBanner } from '@/components/shared/Feedback';

interface AgentFlowPanelProps { patientId: string; compact?: boolean; audience?: 'clinical' | 'nurse'; onOpenReview?: (reviewType: string) => void; }

export default function AgentFlowPanel({ patientId, compact = false, audience = 'clinical', onOpenReview }: AgentFlowPanelProps) {
  const [expanded, setExpanded] = useState(!compact);
  const [selectedStageId, setSelectedStageId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ['agent-flow', patientId], queryFn: () => fetchAgentFlow(patientId), enabled: Boolean(patientId), refetchInterval: 30_000 });
  if (query.isLoading) return <Card variant="outlined" sx={{ p: 2, borderRadius: 1 }}><CircularProgress size={20} /></Card>;
  if (query.error || !query.data) return <ErrorBanner message="智能流程状态加载失败" onRetry={() => void query.refetch()} />;
  const flow = normalizeAgentFlow(query.data);
  const summary = agentFlowSummary(flow.stages);
  return <Card variant="outlined" sx={{ borderRadius: 1, overflow: 'hidden' }}>
    <Box sx={{ px: 1.75, py: 1.25, display: 'flex', alignItems: 'center', gap: 0.75, borderBottom: expanded ? '1px solid' : 0, borderColor: 'divider' }}>
      <Bot size={18} /><Box sx={{ minWidth: 0, flex: 1 }}><Typography variant="subtitle2" fontWeight={600}>{audience === 'nurse' ? '护理智能流程与证据' : '智能流程与生成内容'}</Typography><Typography variant="caption" color="text.secondary">区分规则、RAG、LLM 与人工确认</Typography></Box>
      <Chip size="small" variant="outlined" label={`状态版本 v${flow.state_version}`} />
      <Chip size="small" color={flow.flow_status === 'waiting_review' ? 'warning' : 'success'} label={flow.flow_status === 'waiting_review' ? (audience === 'nurse' ? '待护士复核' : '等待审核') : '流程就绪'} />
      {flow.pending_review && onOpenReview ? <Button size="small" variant="contained" color="warning" endIcon={<ArrowRight size={14} />} onClick={() => onOpenReview(flow.pending_review!.review_type)}>去审核：{flow.pending_review.label}</Button> : null}
      <Tooltip title="刷新流程状态"><IconButton size="small" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw size={18} /></IconButton></Tooltip>
      <Tooltip title={expanded ? '收起流程' : '展开流程'}><IconButton size="small" onClick={() => setExpanded((value) => !value)}>{expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</IconButton></Tooltip>
    </Box>
    {expanded ? <Box sx={{ p: 1.75, display: 'flex', flexDirection: 'column', gap: 1.5 }}>
      <FlowOverview summary={summary} stateVersion={flow.state_version} />
      <FlowStages stages={flow.stages} selectedId={selectedStageId ?? summary.current?.id ?? flow.stages[0]?.id} onSelect={setSelectedStageId} />
      {(() => {
        const selectedStage = flow.stages.find((stage) => stage.id === (selectedStageId ?? summary.current?.id)) ?? summary.current ?? flow.stages[0];
        return selectedStage ? <StageDetail stage={selectedStage} audience={audience} reviewType={flow.pending_review?.review_type} onOpenReview={onOpenReview} /> : null;
      })()}
      <LatestExecution execution={flow.latest_execution} />
      <TurnJournal entries={flow.turn_journal} />
      {flow.pending_review && onOpenReview ? <Alert severity="warning" action={<Button size="small" color="inherit" onClick={() => onOpenReview(flow.pending_review!.review_type)}>打开审核</Button>}>当前流程卡在“{flow.pending_review.label}”，需医生处理后 Agent 才会继续执行下一节点。</Alert> : null}
      {!compact ? <><Divider /><Artifacts artifacts={flow.generated_artifacts} /><Citations citations={flow.citations} /><Alert severity="info" icon={<ShieldCheck size={17} />}>{flow.safety_boundary}</Alert></> : null}
    </Box> : null}
  </Card>;
}

function FlowOverview({ summary, stateVersion }: { summary: ReturnType<typeof agentFlowSummary>; stateVersion: number }) {
  const progress = summary.total ? Math.round((summary.completed / summary.total) * 100) : 0;
  return <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'minmax(0, 1.3fr) minmax(180px, 0.7fr)' }, gap: 1.25, p: 1.25, border: '1px solid', borderColor: 'divider', bgcolor: 'rgba(11, 100, 114, 0.035)' }}>
    <Box sx={{ minWidth: 0 }}>
      <Typography variant="caption" color="text.secondary">当前 Agent 节点</Typography>
      <Typography variant="body2" fontWeight={600} sx={{ mt: 0.2 }}>{summary.current?.title || (summary.total ? '流程节点已完成' : '暂无流程节点')}</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.25 }}>{summary.current?.description || '当前没有等待人工处理的节点。'} · 页面数据版本 v{stateVersion}</Typography>
    </Box>
    <Box sx={{ minWidth: 0, alignSelf: 'center' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', gap: 1, mb: 0.45 }}><Typography variant="caption" color="text.secondary">流程进度</Typography><Typography variant="caption" fontWeight={600}>{summary.completed}/{summary.total} 节点已完成</Typography></Box>
      <LinearProgress variant="determinate" value={progress} sx={{ height: 6 }} />
    </Box>
  </Box>;
}

function FlowStages({ stages, selectedId, onSelect }: { stages: AgentFlowResponse['stages']; selectedId?: string; onSelect: (stageId: string) => void }) { return <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: `repeat(${Math.min(stages.length, 5)}, minmax(0, 1fr))` }, gap: 0.75 }}>{stages.length ? stages.map((stage, index) => <ButtonBase key={stage.id} onClick={() => onSelect(stage.id)} sx={{ display: 'block', minWidth: 0, textAlign: 'left', width: '100%' }}><Box sx={{ minWidth: 0, height: '100%', position: 'relative', border: '1px solid', borderColor: selectedId === stage.id ? 'primary.main' : stage.status === 'pending' ? 'warning.main' : 'divider', bgcolor: stage.status === 'pending' ? 'warning.light' : selectedId === stage.id ? 'action.selected' : 'background.paper', p: 1.05 }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.65, color: modeColor(stage.mode) }}><ModeIcon mode={stage.mode} /><Typography variant="caption" fontWeight={700}>{index + 1}</Typography><Chip size="small" variant="outlined" label={stageModeLabel(stage.mode)} sx={{ ml: 'auto' }} /></Box><Typography variant="body2" fontWeight={600}>{stage.title}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.35, minHeight: 36 }}>{stage.description}</Typography><Chip size="small" color={stage.status === 'pending' ? 'warning' : stage.status === 'completed' ? 'success' : 'default'} variant={stage.status === 'pending' ? 'filled' : 'outlined'} label={stageStatusLabel(stage.status)} sx={{ mt: 0.7 }} />{stage.outputs.slice(0, 2).map((output) => <Typography key={output} variant="caption" sx={{ display: 'block', mt: 0.45, color: stage.status === 'pending' ? 'warning.dark' : 'text.secondary' }}>• {output}</Typography>)}{stage.status === 'completed' ? <CheckCircle2 size={14} style={{ position: 'absolute', top: 9, right: 9, color: '#2e7d32' }} /> : null}</Box></ButtonBase>) : <Typography variant="body2" color="text.secondary">当前没有可展示的 Agent 节点。</Typography>}</Box>; }

function StageDetail({ stage, audience, reviewType, onOpenReview }: { stage: AgentFlowResponse['stages'][number]; audience: 'clinical' | 'nurse'; reviewType?: string; onOpenReview?: (reviewType: string) => void }) {
  const isHumanGate = stage.mode === 'human';
  const inputs = stage.inputs ?? [];
  return <Card variant="outlined" sx={{ p: 1.35, bgcolor: 'background.default' }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.7, flexWrap: 'wrap' }}><Typography variant="subtitle2">节点详情 · {stage.title}</Typography><Chip size="small" variant="outlined" label={stageModeLabel(stage.mode)} /><Chip size="small" color={stage.status === 'pending' ? 'warning' : stage.status === 'completed' ? 'success' : 'default'} label={stageStatusLabel(stage.status)} /><Typography variant="caption" color="text.secondary" sx={{ ml: { md: 'auto' } }}>点击上方节点可切换</Typography></Box><Typography variant="body2" color="text.secondary" sx={{ mt: 0.7, lineHeight: 1.55 }}>{stageModeDescription(stage.mode)}</Typography><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: 'repeat(3, minmax(0, 1fr))' }, gap: 1, mt: 1 }}><Box sx={{ p: 1, border: '1px solid', borderColor: 'divider' }}><Typography variant="caption" color="text.secondary">本节点输入</Typography>{inputs.length ? inputs.map((input) => <Typography key={input} variant="body2" sx={{ mt: 0.3 }}>· {input}</Typography>) : <Typography variant="body2" color="text.secondary" sx={{ mt: 0.3 }}>暂无结构化输入</Typography>}</Box><Box sx={{ p: 1, border: '1px solid', borderColor: 'divider' }}><Typography variant="caption" color="text.secondary">本节点说明</Typography><Typography variant="body2" sx={{ mt: 0.3 }}>{stage.description}</Typography></Box><Box sx={{ p: 1, border: '1px solid', borderColor: 'divider' }}><Typography variant="caption" color="text.secondary">本节点产出</Typography>{stage.outputs.length ? stage.outputs.map((output) => <Typography key={output} variant="body2" sx={{ mt: 0.3 }}>· {output}</Typography>) : <Typography variant="body2" color="text.secondary" sx={{ mt: 0.3 }}>尚无产出</Typography>}</Box></Box>{isHumanGate ? <Alert severity="warning" sx={{ mt: 1 }} action={reviewType && onOpenReview ? <Button size="small" color="inherit" onClick={() => onOpenReview(reviewType)}>打开审核</Button> : undefined}>{audience === 'nurse' ? '该节点需要护理侧配合完成数据核对，最终临床审核仍由医生负责。' : '该节点必须由医生核对、修改或签署，Agent 不会代替医生完成确认。'}</Alert> : null}</Card>;
}

function LatestExecution({ execution }: { execution?: AgentExecutionTrace | null }) {
  if (!execution) return null;
  const failed = execution.status === 'failed';
  const occurredAt = new Date(execution.occurred_at);
  const timeLabel = Number.isNaN(occurredAt.getTime()) ? execution.occurred_at || '时间未记录' : occurredAt.toLocaleString('zh-CN', { hour12: false });
  return <Box sx={{ p: 1.25, border: '1px solid', borderColor: failed ? 'error.light' : 'divider', bgcolor: failed ? 'error.50' : 'background.default' }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, flexWrap: 'wrap' }}><Clock3 size={16} /><Typography variant="subtitle2">最近一次 Agent 执行</Typography><Chip size="small" color={failed ? 'error' : 'success'} variant="outlined" label={failed ? '执行失败' : '执行完成'} /><Typography variant="caption" color="text.secondary" sx={{ ml: { md: 'auto' } }}>{timeLabel}</Typography></Box><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.55 }}>回路：{agentStrategyLabel(execution.entry_strategy)} · 耗时 {execution.latency_ms} ms · RAG 命中 {execution.rag_hit_count} 条 · 追踪 ID {execution.turn_id || '未记录'}</Typography>{execution.node_path.length ? <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.35 }}>执行节点：{execution.node_path.join(' → ')}</Typography> : null}{failed && execution.error_message ? <Alert severity="error" sx={{ mt: 0.75 }}>{execution.error_message}</Alert> : null}</Box>;
}
function Artifacts({ artifacts }: { artifacts: AgentFlowResponse['generated_artifacts'] }) { return <Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><Sparkles size={16} /><Typography variant="subtitle2">AI 与规则生成内容</Typography></Box>{artifacts.length ? <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: 0.75 }}>{artifacts.map((artifact) => <Box key={artifact.id} sx={{ borderLeft: '3px solid', borderColor: artifact.status.includes('待') ? 'warning.main' : artifact.generator === 'llm' ? 'info.main' : 'success.main', pl: 1, py: 0.35 }}><Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center', flexWrap: 'wrap' }}><Typography variant="body2" fontWeight={600}>{artifact.title}</Typography><Chip size="small" variant="outlined" label={artifact.generator === 'llm' ? 'LLM 辅助' : '规则生成'} /></Box><Typography variant="caption" color="text.secondary" display="block">{artifact.status} · 引用 {artifact.citation_count} 条</Typography><Typography variant="caption" color="text.secondary" display="block">{artifact.guardrail}</Typography></Box>)}</Box> : <Typography variant="body2" color="text.secondary">当前尚未生成可展示的 Agent 内容。</Typography>}</Box>; }
function Citations({ citations }: { citations: AgentFlowResponse['citations'] }) { return <Box>{citations.length ? <><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><SearchCheck size={16} /><Typography variant="subtitle2">本次流程证据</Typography></Box>{citations.slice(0, 4).map((citation, index) => <Box key={`${citation.title}-${index}`} sx={{ borderLeft: '2px solid', borderColor: 'divider', pl: 0.9, py: 0.35, mb: 0.55 }}><Typography variant="caption" fontWeight={600}>{citation.title} · {citation.source}</Typography>{citation.excerpt ? <Typography variant="caption" color="text.secondary" display="block">{citation.excerpt}</Typography> : null}</Box>)}</> : null}</Box>; }
function TurnJournal({ entries }: { entries: AgentFlowResponse['turn_journal'] }) { const formatTime = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '刚刚' : date.toLocaleString('zh-CN', { hour: '2-digit', minute: '2-digit', month: 'numeric', day: 'numeric' }); }; if (!entries.length) return null; return <Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><Clock3 size={16} /><Typography variant="subtitle2">最近执行</Typography></Box><Box sx={{ borderTop: '1px solid', borderColor: 'divider' }}>{entries.map((entry) => <Box key={entry.turn_id} sx={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: 1, py: 0.85, borderBottom: '1px solid', borderColor: 'divider' }}><Box sx={{ minWidth: 0 }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.55, flexWrap: 'wrap' }}><Typography variant="body2" fontWeight={600}>{agentStrategyLabel(entry.entry_strategy)}</Typography><Chip size="small" color={entry.status === 'failed' ? 'error' : entry.knowledge_gap ? 'warning' : 'success'} variant="outlined" label={entry.status === 'failed' ? '执行失败' : entry.knowledge_gap ? '证据待补充' : '已完成'} /></Box><Typography variant="caption" color="text.secondary">{entry.rag_hit_count ? `RAG 命中 ${entry.rag_hit_count} 条` : '未命中额外 RAG 证据'} · 节点 {entry.node_count} 个{entry.error_message ? ` · ${entry.error_message}` : ''}</Typography></Box><Typography variant="caption" color="text.secondary" sx={{ whiteSpace: 'nowrap' }}>{formatTime(entry.occurred_at)} · {entry.latency_ms} ms</Typography></Box>)}</Box></Box>; }
function ModeIcon({ mode }: { mode: AgentFlowMode }) { const Icon = mode === 'rag' ? SearchCheck : mode === 'llm' ? BrainCircuit : mode === 'human' ? UserRoundCheck : mode === 'record' ? FileCheck2 : Database; return <Icon size={16} />; }
function modeColor(mode: AgentFlowMode) { return mode === 'llm' ? 'info.main' : mode === 'human' ? 'warning.dark' : mode === 'rag' ? 'secondary.main' : mode === 'record' ? 'success.main' : 'text.secondary'; }
function stageModeLabel(mode: AgentFlowMode) { return ({ rule: '规则', rag: 'RAG', llm: 'LLM', human: '人工', record: '写回' } as Record<AgentFlowMode, string>)[mode]; }
