import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ArrowRight, Bot, BrainCircuit, CheckCircle2, ChevronDown, ChevronUp, Clock3, Database, FileCheck2, RefreshCw, SearchCheck, ShieldCheck, Sparkles, UserRoundCheck } from 'lucide-react';
import { Alert, Box, Button, Card, Chip, CircularProgress, Divider, IconButton, Tooltip, Typography } from '@mui/material';

import { fetchAgentFlow, normalizeAgentFlow, type AgentFlowMode, type AgentFlowResponse } from '@/services/agent-flow-service';
import { ErrorBanner } from '@/components/shared/Feedback';

interface AgentFlowPanelProps { patientId: string; compact?: boolean; audience?: 'clinical' | 'nurse'; onOpenReview?: (reviewType: string) => void; }

export default function AgentFlowPanel({ patientId, compact = false, audience = 'clinical', onOpenReview }: AgentFlowPanelProps) {
  const [expanded, setExpanded] = useState(!compact);
  const query = useQuery({ queryKey: ['agent-flow', patientId], queryFn: () => fetchAgentFlow(patientId), enabled: Boolean(patientId), refetchInterval: 30_000 });
  if (query.isLoading) return <Card variant="outlined" sx={{ p: 2, borderRadius: 1 }}><CircularProgress size={20} /></Card>;
  if (query.error || !query.data) return <ErrorBanner message="智能流程状态加载失败" onRetry={() => void query.refetch()} />;
  const flow = normalizeAgentFlow(query.data);
  return <Card variant="outlined" sx={{ borderRadius: 1, overflow: 'hidden' }}>
    <Box sx={{ px: 1.75, py: 1.25, display: 'flex', alignItems: 'center', gap: 0.75, borderBottom: expanded ? '1px solid' : 0, borderColor: 'divider' }}>
      <Bot size={18} /><Box sx={{ minWidth: 0, flex: 1 }}><Typography variant="subtitle2" fontWeight={600}>{audience === 'nurse' ? '护理智能流程与证据' : '智能流程与生成内容'}</Typography><Typography variant="caption" color="text.secondary">区分规则、RAG、LLM 与人工确认</Typography></Box>
      <Chip size="small" color={flow.flow_status === 'waiting_review' ? 'warning' : 'success'} label={flow.flow_status === 'waiting_review' ? (audience === 'nurse' ? '待护士复核' : '等待审核') : '流程就绪'} />
      {flow.pending_review && onOpenReview ? <Button size="small" variant="contained" color="warning" endIcon={<ArrowRight size={14} />} onClick={() => onOpenReview(flow.pending_review!.review_type)}>去审核：{flow.pending_review.label}</Button> : null}
      <Tooltip title="刷新流程状态"><IconButton size="small" disabled={query.isFetching} onClick={() => void query.refetch()}><RefreshCw size={18} /></IconButton></Tooltip>
      <Tooltip title={expanded ? '收起流程' : '展开流程'}><IconButton size="small" onClick={() => setExpanded((value) => !value)}>{expanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</IconButton></Tooltip>
    </Box>
    {expanded ? <Box sx={{ p: 1.75, display: 'flex', flexDirection: 'column', gap: 1.5 }}>
      <FlowStages stages={flow.stages} />
      <TurnJournal entries={flow.turn_journal} />
      {flow.pending_review && onOpenReview ? <Alert severity="warning" action={<Button size="small" color="inherit" onClick={() => onOpenReview(flow.pending_review!.review_type)}>打开审核</Button>}>当前流程卡在“{flow.pending_review.label}”，需医生处理后 Agent 才会继续执行下一节点。</Alert> : null}
      {!compact ? <><Divider /><Artifacts artifacts={flow.generated_artifacts} /><Citations citations={flow.citations} /><Alert severity="info" icon={<ShieldCheck size={17} />}>{flow.safety_boundary}</Alert></> : null}
    </Box> : null}
  </Card>;
}

function FlowStages({ stages }: { stages: AgentFlowResponse['stages'] }) { return <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', lg: `repeat(${Math.min(stages.length, 5)}, minmax(0, 1fr))` }, gap: 0.75 }}>{stages.map((stage, index) => <Box key={stage.id} sx={{ minWidth: 0, position: 'relative', border: '1px solid', borderColor: stage.status === 'pending' ? 'warning.main' : stage.status === 'completed' ? 'divider' : 'divider', bgcolor: stage.status === 'pending' ? 'warning.light' : 'background.paper', p: 1.05 }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.65, color: modeColor(stage.mode) }}><ModeIcon mode={stage.mode} /><Typography variant="caption" fontWeight={700}>{index + 1}</Typography></Box><Typography variant="body2" fontWeight={600}>{stage.title}</Typography><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 0.35, minHeight: 36 }}>{stage.description}</Typography>{stage.outputs.slice(0, 2).map((output) => <Typography key={output} variant="caption" sx={{ display: 'block', mt: 0.45, color: stage.status === 'pending' ? 'warning.dark' : 'text.secondary' }}>• {output}</Typography>)}{stage.status === 'completed' ? <CheckCircle2 size={14} style={{ position: 'absolute', top: 9, right: 9, color: '#2e7d32' }} /> : null}</Box>)}</Box>; }
function Artifacts({ artifacts }: { artifacts: AgentFlowResponse['generated_artifacts'] }) { return <Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><Sparkles size={16} /><Typography variant="subtitle2">AI 与规则生成内容</Typography></Box>{artifacts.length ? <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, minmax(0, 1fr))' }, gap: 0.75 }}>{artifacts.map((artifact) => <Box key={artifact.id} sx={{ borderLeft: '3px solid', borderColor: artifact.status.includes('待') ? 'warning.main' : artifact.generator === 'llm' ? 'info.main' : 'success.main', pl: 1, py: 0.35 }}><Box sx={{ display: 'flex', gap: 0.5, alignItems: 'center', flexWrap: 'wrap' }}><Typography variant="body2" fontWeight={600}>{artifact.title}</Typography><Chip size="small" variant="outlined" label={artifact.generator === 'llm' ? 'LLM 辅助' : '规则生成'} /></Box><Typography variant="caption" color="text.secondary" display="block">{artifact.status} · 引用 {artifact.citation_count} 条</Typography><Typography variant="caption" color="text.secondary" display="block">{artifact.guardrail}</Typography></Box>)}</Box> : <Typography variant="body2" color="text.secondary">当前尚未生成可展示的 Agent 内容。</Typography>}</Box>; }
function Citations({ citations }: { citations: AgentFlowResponse['citations'] }) { return <Box>{citations.length ? <><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><SearchCheck size={16} /><Typography variant="subtitle2">本次流程证据</Typography></Box>{citations.slice(0, 4).map((citation, index) => <Box key={`${citation.title}-${index}`} sx={{ borderLeft: '2px solid', borderColor: 'divider', pl: 0.9, py: 0.35, mb: 0.55 }}><Typography variant="caption" fontWeight={600}>{citation.title} · {citation.source}</Typography>{citation.excerpt ? <Typography variant="caption" color="text.secondary" display="block">{citation.excerpt}</Typography> : null}</Box>)}</> : null}</Box>; }
function TurnJournal({ entries }: { entries: AgentFlowResponse['turn_journal'] }) { const formatTime = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '刚刚' : date.toLocaleString('zh-CN', { hour: '2-digit', minute: '2-digit', month: 'numeric', day: 'numeric' }); }; if (!entries.length) return null; return <Box><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.65, mb: 0.75 }}><Clock3 size={16} /><Typography variant="subtitle2">最近执行</Typography></Box><Box sx={{ borderTop: '1px solid', borderColor: 'divider' }}>{entries.map((entry) => <Box key={entry.turn_id} sx={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: 1, py: 0.85, borderBottom: '1px solid', borderColor: 'divider' }}><Box sx={{ minWidth: 0 }}><Box sx={{ display: 'flex', alignItems: 'center', gap: 0.55, flexWrap: 'wrap' }}><Typography variant="body2" fontWeight={600}>{entry.entry_strategy}</Typography><Chip size="small" color={entry.status === 'failed' ? 'error' : entry.knowledge_gap ? 'warning' : 'success'} variant="outlined" label={entry.status === 'failed' ? '执行失败' : entry.knowledge_gap ? '证据待补充' : '已完成'} /></Box><Typography variant="caption" color="text.secondary">{entry.rag_hit_count ? `RAG 命中 ${entry.rag_hit_count} 条` : '未命中额外 RAG 证据'} · 节点 {entry.node_count} 个{entry.error_message ? ` · ${entry.error_message}` : ''}</Typography></Box><Typography variant="caption" color="text.secondary" sx={{ whiteSpace: 'nowrap' }}>{formatTime(entry.occurred_at)} · {entry.latency_ms} ms</Typography></Box>)}</Box></Box>; }
function ModeIcon({ mode }: { mode: AgentFlowMode }) { const Icon = mode === 'rag' ? SearchCheck : mode === 'llm' ? BrainCircuit : mode === 'human' ? UserRoundCheck : mode === 'record' ? FileCheck2 : Database; return <Icon size={16} />; }
function modeColor(mode: AgentFlowMode) { return mode === 'llm' ? 'info.main' : mode === 'human' ? 'warning.dark' : mode === 'rag' ? 'secondary.main' : mode === 'record' ? 'success.main' : 'text.secondary'; }
