import { useEffect, useState } from 'react';
import { Alert, Box, Button, Card, Checkbox, FormControlLabel, MenuItem, TextField, Typography } from '@mui/material';
import { ContactRound, LockKeyhole, Phone } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';

import { fetchFollowUpContact, saveFollowUpContact, type FollowUpContact } from '@/services/patient-service';

export default function FollowUpContactPanel({ patientId }: { patientId: string }) {
  const queryClient = useQueryClient();
  const contact = useQuery({ queryKey: ['patient', patientId, 'follow-up-contact'], queryFn: () => fetchFollowUpContact(patientId), staleTime: 30_000 });
  const [form, setForm] = useState<FollowUpContact>({ follow_up_consent: false, contact_version: 0, preferred_channel: 'phone' });
  const [saved, setSaved] = useState(false);
  useEffect(() => { if (contact.data?.contact) setForm(contact.data.contact); }, [contact.data]);
  const mutation = useMutation({ mutationFn: () => saveFollowUpContact(patientId, { mobile_phone: form.mobile_phone || undefined, alternate_contact_name: form.alternate_contact_name || undefined, alternate_contact_relation: form.alternate_contact_relation || undefined, alternate_contact_phone: form.alternate_contact_phone || undefined, preferred_channel: form.preferred_channel || 'phone', follow_up_consent: form.follow_up_consent, expected_contact_version: form.contact_version }), onSuccess: async () => { setSaved(true); await queryClient.invalidateQueries({ queryKey: ['patient'] }); await queryClient.invalidateQueries({ queryKey: ['ward'] }); await queryClient.invalidateQueries({ queryKey: ['patient', patientId, 'follow-up-contact'] }); await queryClient.invalidateQueries({ queryKey: ['follow-up'] }); } });
  const update = <K extends keyof FollowUpContact>(key: K, value: FollowUpContact[K]) => setForm((current) => ({ ...current, [key]: value }));
  const canSave = !form.follow_up_consent || Boolean(form.mobile_phone?.trim());

  return <Card variant="outlined" sx={{ borderRadius: 1 }}><Box sx={{ px: 1.75, py: 1.2, display: 'flex', gap: 0.75, alignItems: 'center', borderBottom: '1px solid', borderColor: 'divider' }}><ContactRound size={18} /><Typography variant="subtitle2" fontWeight={600}>随访联系方式</Typography><LockKeyhole size={15} style={{ marginLeft: 'auto' }} /></Box><Box sx={{ p: 1.5, display: 'flex', flexDirection: 'column', gap: 1.1 }}>{contact.error ? <Alert severity="error">联系方式读取失败，请稍后重试。</Alert> : null}<FormControlLabel control={<Checkbox checked={form.follow_up_consent} onChange={(event) => update('follow_up_consent', event.target.checked)} />} label="患者已授权出院后随访联系" /><TextField size="small" label="患者手机号" value={form.mobile_phone ?? ''} onChange={(event) => update('mobile_phone', event.target.value)} disabled={!form.follow_up_consent || contact.isLoading} required={form.follow_up_consent} InputProps={{ startAdornment: <Phone size={16} style={{ marginRight: 8 }} /> }} /><TextField select size="small" label="首选联系渠道" value={form.preferred_channel ?? 'phone'} onChange={(event) => update('preferred_channel', event.target.value as FollowUpContact['preferred_channel'])} disabled={!form.follow_up_consent}><MenuItem value="phone">电话</MenuItem><MenuItem value="sms">短信</MenuItem><MenuItem value="wechat">微信</MenuItem></TextField><Box sx={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 110px', gap: 1 }}><TextField size="small" label="备用联系人" value={form.alternate_contact_name ?? ''} onChange={(event) => update('alternate_contact_name', event.target.value)} disabled={!form.follow_up_consent} /><TextField size="small" label="关系" value={form.alternate_contact_relation ?? ''} onChange={(event) => update('alternate_contact_relation', event.target.value)} disabled={!form.follow_up_consent} /></Box><TextField size="small" label="备用联系电话" value={form.alternate_contact_phone ?? ''} onChange={(event) => update('alternate_contact_phone', event.target.value)} disabled={!form.follow_up_consent} /><Typography variant="caption" color="text.secondary">联系方式加密保存；查看和更新均会进入审计。撤回授权后系统将清除已登记的联系信息。</Typography>{mutation.error ? <Alert severity="error">{mutation.error instanceof Error ? mutation.error.message : '联系方式保存失败'}</Alert> : null}{saved && !mutation.isPending ? <Alert severity="success">联系方式已保存，出院流程阻塞项已自动更新。</Alert> : null}<Box sx={{ display: 'flex', justifyContent: 'flex-end' }}><Button size="small" variant="outlined" disabled={!canSave || mutation.isPending || contact.isLoading} onClick={() => mutation.mutate()}>{mutation.isPending ? '保存中...' : form.follow_up_consent ? '保存联系方式' : '确认撤回授权'}</Button></Box></Box></Card>;
}
