"""initial schema

Revision ID: aca523271c20
Revises: 
Create Date: 2026-08-11 09:56:49.652486

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca523271c20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot_id', sa.String(length=64), nullable=True),
    sa.Column('patient_ref', sa.String(length=256), nullable=True),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('before_state', sa.String(length=32), nullable=True),
    sa.Column('after_state', sa.String(length=32), nullable=True),
    sa.Column('workflow_version', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_case_ts', 'audit_events', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_audit_id'), 'audit_events', ['audit_id'], unique=True)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('risk_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('severity_label', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('citation_excerpt', sa.Text(), nullable=True),
    sa.Column('citation_document_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_items_case_id'), 'risk_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_risk_items_risk_id'), 'risk_items', ['risk_id'], unique=True)
    op.create_table('task_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sop_version', sa.String(length=32), nullable=True),
    sa.Column('tasks_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_drafts_case_id'), 'task_drafts', ['case_id'], unique=False)
    op.create_index(op.f('ix_task_drafts_draft_id'), 'task_drafts', ['draft_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_drafts_draft_id'), table_name='task_drafts')
    op.drop_index(op.f('ix_task_drafts_case_id'), table_name='task_drafts')
    op.drop_table('task_drafts')
    op.drop_index(op.f('ix_risk_items_risk_id'), table_name='risk_items')
    op.drop_index(op.f('ix_risk_items_case_id'), table_name='risk_items')
    op.drop_table('risk_items')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_audit_id'), table_name='audit_events')
    op.drop_index('idx_audit_case_ts', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
